spring:
  data:
    mongodb:
      port: 27017
      database: bookdb
      host: localhost

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.lec13.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local